name: Generate pacman animation

on:
  schedule: # executa a cada 12 horas
    - cron: "0 */12 * * *"

  workflow_dispatch: # permite rodar manualmente

  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # 1️⃣ Clona o repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Gera o gráfico Pac-Man
      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      # 3️⃣ Publica o resultado no branch 'output'
      - name: Push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
